spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # create: application 실행 시점에 내가 가진거 다 지우고 다시 생성함
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true # system out을 통해 찍는다.
        format_sql: true

logging.level:
  org.hibernate.SQL: debug # logger 를 통해 찍는다
  org.hibernate.type: trace
